services:
  scribberr:
    image: ghcr.io/rishikanthc/scriberr:latest
    container_name: scribberr
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - scriberr_data:/app/data
    networks:
      - mon_reseau_front

networks:
  mon_reseau_front:
    external: true

volumes:
  scriberr_data:
